# Generated by Django 2.0 on 2018-01-04 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180103_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('alt', models.CharField(max_length=200)),
                ('url_link', models.URLField()),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Project')),
            ],
        ),
    ]
