# Generated by Django 2.0 on 2018-01-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='little_description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
