# Generated by Django 2.0 on 2018-01-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_project_little_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='source_image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='source_image_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_image_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='trinket',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='url_link',
            field=models.URLField(null=True),
        ),
    ]
