# Generated by Django 2.0 on 2018-01-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180105_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
